### ISSUE TITLE
Not able to upgrade Ubuntu 14.10 to 16.04

### ISSUE THREAD

**Issue by jsroyal** [rhannequin/upgrade-ubuntu#6]
Hey!  @rhannequin Could you please help me ?
I am stuck  here to upgrade Ubuntu  and getting error and not finding any clue?

Third party sources disabled

Some third party entries in your sources.list were disabled. You can re-enable them after the upgrade with the 'software-properties' tool or your package manager.

How to enable them?
some snapshot.
![image](https://cloud.githubusercontent.com/assets/10773353/23846974/30a63b8e-07f6-11e7-8935-df203d42a0f6.png)

![image](https://cloud.githubusercontent.com/assets/10773353/23846994/413f44ae-07f6-11e7-9c64-2885c19445cc.png)
![image](https://cloud.githubusercontent.com/assets/10773353/23847006/501e14fa-07f6-11e7-9a35-f8756346e820.png)

![image](https://cloud.githubusercontent.com/assets/10773353/23847020/65932c94-07f6-11e7-8f08-52444d3aa347.png)

**Comment by rhannequin** [comment]
Hi @jsroyal, it is supposed to be in the "Other Softwares" section. Be sure to enable all of the sources.

Your problem may come from the fact that some packages were available in 14.04 but not in 16.04. Check in you `/etc/apt/sources.list.d/` directory to see you third party sources. Maybe you'll find the one that doesn't work anymore. In that case, check on the internet if the packages are not availale from other sources, you can find that on packages.ubuntu.com.

Good luck!

**Comment by jsroyal** [comment]
@rhannequin Thank you. I appreciate your comment.
But anyway I resolved my this issue.
Actually, My Ubuntu 14.10 OS was  not Long Term Support (LTS) version  so it won't direct upgrade 14.10 to 16.04.
A bad Googling  go to give path me only I can upgrade through this way.
14.10 -> 15.04 ->15.10 -> 16.04 and I did it because there was not alter for upgrade .
 
So I want to close this issue.
